---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-reader
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops
  namespace: default